DROP DATABASE IF EXISTS flaffy;
CREATE DATABASE flaffy;
USE flaffy;
CREATE TABLE zapa( 
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    foto VARCHAR(255) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    precio VARCHAR(255) NOT NULL
);